// 스타크래프트 맵 데이터 상수
//
// 각 맵의 특성:
/// - rushDistance: 러시거리 (0.0~1.0, 높을수록 멀다)
/// - resources: 자원량 (0.0~1.0, 높을수록 풍부)
/// - complexity: 복잡도 (0.0~1.0, 높을수록 복잡)
/// - tvz: TvZ 테란 승률 (35~65)
/// - zvp: ZvP 저그 승률 (35~65)
/// - pvt: PvT 프로토스 승률 (35~65)

import '../../domain/models/game_map.dart';

class MapData {
  final String name;
  final String imageFile;
  final double rushDistance;
  final double resources;
  final double complexity;
  final int tvz;
  final int zvp;
  final int pvt;
  final String? description;

  const MapData({
    required this.name,
    required this.imageFile,
    required this.rushDistance,
    required this.resources,
    required this.complexity,
    required this.tvz,
    required this.zvp,
    required this.pvt,
    this.description,
  });

  /// MapData → GameMap 변환 (시뮬레이션용)
  GameMap toGameMap() {
    final rd = (rushDistance * 10).round().clamp(1, 10);
    final res = (resources * 10).round().clamp(1, 10);
    final comp = (complexity * 10).round().clamp(1, 10);

    return GameMap(
      id: name,
      name: name,
      rushDistance: rd,
      resources: res,
      complexity: comp,
      matchup: RaceMatchup(
        tvzTerranWinRate: tvz.clamp(35, 65),
        zvpZergWinRate: zvp.clamp(35, 65),
        pvtProtossWinRate: pvt.clamp(35, 65),
      ),
      expansionCount: res >= 7 ? 5 : res >= 5 ? 4 : 3,
      terrainComplexity: comp,
      airAccessibility: rd >= 7 ? 7 : rd >= 5 ? 6 : 5,
      centerImportance: rd <= 4 ? 8 : rd <= 6 ? 6 : 4,
      hasIsland: description?.contains('섬') == true ||
          description?.contains('아일랜드') == true,
    );
  }
}

/// 전체 맵 목록 (가나다순, 219개)
const List<MapData> allMaps = [
  // 숫자
  MapData(
    name: '76',
    imageFile: '76.gif',
    rushDistance: 0.4,
    resources: 0.6,
    complexity: 0.5,
    tvz: 58, zvp: 52, pvt: 44,
    description: '4인용, 고속도로 컨셉, 빠른 병력 이동으로 테란 기계화 유리',
  ),
  MapData(
    name: '815',
    imageFile: '815.gif',
    rushDistance: 0.6,
    resources: 0.7,
    complexity: 0.5,
    tvz: 50, zvp: 50, pvt: 50,
    description: '4인용, 광복절 테마 대칭맵, 종족 밸런스 균형',
  ),

  // ㄱ
  MapData(
    name: '가이아',
    imageFile: '가이아.gif',
    rushDistance: 0.7,
    resources: 0.8,
    complexity: 0.5,
    tvz: 44, zvp: 56, pvt: 50,
    description: '4인용, 자연 지형 테마, 풍부한 자원과 넓은 멀티로 저그 유리',
  ),
  MapData(
    name: '개마고원',
    imageFile: '개마고원.gif',
    rushDistance: 0.8,
    resources: 0.7,
    complexity: 0.4,
    tvz: 42, zvp: 58, pvt: 48,
    description: '4인용, 한반도 북부 고원 테마, 먼 러시거리와 넓은 평원으로 저그맵',
  ),
  MapData(
    name: '개척시대',
    imageFile: '개척시대.gif',
    rushDistance: 0.7,
    resources: 0.7,
    complexity: 0.4,
    tvz: 45, zvp: 55, pvt: 48,
    description: '4인용, 서부개척 테마, 넓은 평원과 멀티 풍부, 저그 선호',
  ),
  MapData(
    name: '건틀릿',
    imageFile: '건틀릿.gif',
    rushDistance: 0.4,
    resources: 0.5,
    complexity: 0.7,
    tvz: 57, zvp: 48, pvt: 42,
    description: '좁은 초크 포인트, 시즈탱크 포진 유리한 테란맵',
  ),
  MapData(
    name: '골드러쉬',
    imageFile: '골드러쉬.gif',
    rushDistance: 0.55,
    resources: 0.85,
    complexity: 0.6,
    tvz: 52, zvp: 55, pvt: 47,
    description: '3인용, 금광 쟁탈 3갈래 구조, 자원 풍부하여 매크로전 유도',
  ),
  MapData(
    name: '굿나잇',
    imageFile: '굿나잇.gif',
    rushDistance: 0.6,
    resources: 0.6,
    complexity: 0.7,
    tvz: 48, zvp: 52, pvt: 50,
    description: '4인용, 밤 테마 어두운 타일셋, 복잡한 지형에서 매복 유리',
  ),
  MapData(
    name: '그랜드라인',
    imageFile: '그랜드라인.gif',
    rushDistance: 0.6,
    resources: 0.7,
    complexity: 0.6,
    tvz: 60, zvp: 45, pvt: 51,
    description: '멀티 획득 쉬우나 방어 어려움, 테란맵',
  ),
  MapData(
    name: '그레이트배리어리프',
    imageFile: '그레이트배리어리프.gif',
    rushDistance: 0.65,
    resources: 0.7,
    complexity: 0.7,
    tvz: 45, zvp: 55, pvt: 55,
    description: '3인용, 산호초 해양 타일셋, 섬멀티 포함, 공중 유닛 활용 중요',
  ),
  MapData(
    name: '글레디에이터',
    imageFile: '글레디에이터.gif',
    rushDistance: 0.5,
    resources: 0.6,
    complexity: 0.6,
    tvz: 55, zvp: 48, pvt: 55,
    description: '역언덕 상성맵, 상성 우위 종족 초반 압박 강력',
  ),
  MapData(
    name: '기요틴',
    imageFile: '기요틴.gif',
    rushDistance: 0.4,
    resources: 0.5,
    complexity: 0.7,
    tvz: 57, zvp: 50, pvt: 44,
    description: '4인용, 좁은 초크와 압박형 구조, 짧은 러시거리로 테란맵',
  ),

  // ㄴ
  MapData(
    name: '남자이야기',
    imageFile: '남자이야기.gif',
    rushDistance: 0.5,
    resources: 0.6,
    complexity: 0.4,
    tvz: 55, zvp: 50, pvt: 45,
    description: '4인용, 직선적 구조와 단순한 지형, 테란 약간 유리',
  ),
  MapData(
    name: '네메시스',
    imageFile: '네메시스.gif',
    rushDistance: 0.5,
    resources: 0.6,
    complexity: 0.5,
    tvz: 52, zvp: 50, pvt: 48,
    description: '4인용, 복수의 여신 테마, 대칭형 중앙 전투 중심맵',
  ),
  MapData(
    name: '네오그라운드제로',
    imageFile: '네오그라운드제로.gif',
    rushDistance: 0.7,
    resources: 0.7,
    complexity: 0.4,
    tvz: 55, zvp: 48, pvt: 48,
    description: '중앙집중형 힘싸움맵, 넓은 중앙, 테란 유리',
  ),
  MapData(
    name: '네오문글레이브',
    imageFile: '네오문글레이브.gif',
    rushDistance: 0.6,
    resources: 0.6,
    complexity: 0.5,
    tvz: 60, zvp: 40, pvt: 65,
    description: '3인용, 역언덕 힘싸움맵, 저그 불리',
  ),
  MapData(
    name: '네오벨트웨이',
    imageFile: '네오벨트웨이.gif',
    rushDistance: 0.7,
    resources: 0.7,
    complexity: 0.5,
    tvz: 55, zvp: 48, pvt: 48,
    description: '도넛형 센터, 벌처 운영 유리, 테란맵',
  ),
  MapData(
    name: '네오아웃라이어',
    imageFile: '네오아웃라이어.gif',
    rushDistance: 0.6,
    resources: 0.5,
    complexity: 0.6,
    tvz: 35, zvp: 50, pvt: 55,
    description: '3인용, 역언덕, 테란 압살맵, 저그 극유리',
  ),
  MapData(
    name: '네오아즈텍',
    imageFile: '네오아즈텍.gif',
    rushDistance: 0.6,
    resources: 0.6,
    complexity: 0.6,
    tvz: 53, zvp: 53, pvt: 50,
    description: '개념맵, 탱크 드랍 유리한 언덕 지형',
  ),
  MapData(
    name: '네오일렉트릭써킷',
    imageFile: '네오일렉트릭써킷.gif',
    rushDistance: 0.6,
    resources: 0.6,
    complexity: 0.6,
    tvz: 52, zvp: 50, pvt: 50,
    description: '중립건물 특징, 스플래시 유닛 중요',
  ),
  MapData(
    name: '네오제이드',
    imageFile: '네오제이드.gif',
    rushDistance: 0.7,
    resources: 0.6,
    complexity: 0.5,
    tvz: 50, zvp: 60, pvt: 64,
    description: '역언덕, 러시거리 긺, 뮤탈 활용 유리, 저그맵',
  ),
  MapData(
    name: '네오체인리액션',
    imageFile: '네오체인리액션.gif',
    rushDistance: 0.7,
    resources: 0.6,
    complexity: 0.5,
    tvz: 42, zvp: 65, pvt: 55,
    description: '저그맵, 저프전 저그 압도적 유리',
  ),
  MapData(
    name: '노스탤지아',
    imageFile: '노스탤지아.gif',
    rushDistance: 0.6,
    resources: 0.6,
    complexity: 0.5,
    tvz: 50, zvp: 50, pvt: 50,
    description: '4인용, 향수 테마 클래식 구조, 밸런스 개념맵',
  ),
  MapData(
    name: '녹아웃',
    imageFile: '녹아웃.gif',
    rushDistance: 0.5,
    resources: 0.5,
    complexity: 0.6,
    tvz: 54, zvp: 50, pvt: 46,
    description: '4인용, 격투 테마, 중앙 교전이 승패를 결정하는 힘싸움맵',
  ),

  // ㄷ
  MapData(
    name: '다크오리진',
    imageFile: '다크오리진.gif',
    rushDistance: 0.5,
    resources: 0.6,
    complexity: 0.7,
    tvz: 47, zvp: 55, pvt: 48,
    description: '어둠 타일셋, 다중 진출로로 수비 어려운 저그맵',
  ),
  MapData(
    name: '단장의능선',
    imageFile: '단장의능선.gif',
    rushDistance: 0.6,
    resources: 0.6,
    complexity: 0.7,
    tvz: 49, zvp: 57, pvt: 59,
    description: '2인용, 능선 지형 복잡, 러커 활용 유리, 저그맵',
  ),
  MapData(
    name: '단테스피크SE',
    imageFile: '단테스피크SE.gif',
    rushDistance: 0.5,
    resources: 0.7,
    complexity: 0.6,
    tvz: 50, zvp: 65, pvt: 35,
    description: '멀티 가깝고 방어 용이, 저그맵, 프토 불리',
  ),
  MapData(
    name: '달의눈물',
    imageFile: '달의눈물.gif',
    rushDistance: 0.6,
    resources: 0.5,
    complexity: 0.5,
    tvz: 45, zvp: 65, pvt: 35,
    description: '3인용, 입구 2개, 프토 불리, 저그맵',
  ),
  MapData(
    name: '데미안',
    imageFile: '데미안.gif',
    rushDistance: 0.6,
    resources: 0.5,
    complexity: 0.8,
    tvz: 48, zvp: 52, pvt: 53,
    description: '3인용, 어둠 테마, 복잡한 언덕 지형으로 매복과 고지대 전투 다발',
  ),
  MapData(
    name: '데스밸리',
    imageFile: '데스밸리.gif',
    rushDistance: 0.5,
    resources: 0.5,
    complexity: 0.5,
    tvz: 55, zvp: 52, pvt: 48,
    description: '평지 계곡 지형, 병력 교전 중심의 테란맵',
  ),
  MapData(
    name: '데스티네이션',
    imageFile: '데스티네이션.gif',
    rushDistance: 0.7,
    resources: 0.6,
    complexity: 0.7,
    tvz: 58, zvp: 50, pvt: 55,
    description: '2인용, 언덕 지형 활용, 메카닉 테란 유리',
  ),
  MapData(
    name: '데스페라도',
    imageFile: '데스페라도.gif',
    rushDistance: 0.5,
    resources: 0.8,
    complexity: 0.5,
    tvz: 48, zvp: 45, pvt: 65,
    description: '본진 10미네랄+2가스, 토스맵 삼대장',
  ),
  MapData(
    name: '데자뷰',
    imageFile: '데자뷰.gif',
    rushDistance: 0.6,
    resources: 0.6,
    complexity: 0.5,
    tvz: 48, zvp: 48, pvt: 50,
    description: '4인용, 기시감 테마, 반복 대칭 구조의 밸런스맵',
  ),
  MapData(
    name: '데저트폭스',
    imageFile: '데저트폭스.gif',
    rushDistance: 0.6,
    resources: 0.55,
    complexity: 0.5,
    tvz: 55, zvp: 52, pvt: 42,
    description: '3인용, 사막 테마, 넓은 평지와 기동전 중심, 테란맵',
  ),
  MapData(
    name: '데토네이션F',
    imageFile: '데토네이션F.gif',
    rushDistance: 0.6,
    resources: 0.6,
    complexity: 0.5,
    tvz: 45, zvp: 55, pvt: 48,
    description: '저그맵, 저그가 양 종족 상대 유리',
  ),
  MapData(
    name: '도미네이터',
    imageFile: '도미네이터.gif',
    rushDistance: 0.6,
    resources: 0.55,
    complexity: 0.65,
    tvz: 55, zvp: 48, pvt: 48,
    description: '3인용, 중앙 고지대 쟁탈전 중심, 시즈탱크 포지션 유리한 테란맵',
  ),
  MapData(
    name: '디아이',
    imageFile: '디아이.gif',
    rushDistance: 0.6,
    resources: 0.5,
    complexity: 0.6,
    tvz: 46, zvp: 55, pvt: 48,
    description: '4인용, 눈 테마, 중앙 고지대 시야 확보가 핵심인 저그맵',
  ),

  // ㄹ
  MapData(
    name: '라그나로크',
    imageFile: '라그나로크.gif',
    rushDistance: 0.8,
    resources: 0.8,
    complexity: 0.7,
    tvz: 42, zvp: 58, pvt: 50,
    description: '4인용, 북유럽 신화 테마, 거대 지형과 풍부한 자원으로 저그 유리',
  ),
  MapData(
    name: '라데온',
    imageFile: '라데온.gif',
    rushDistance: 0.5,
    resources: 0.6,
    complexity: 0.7,
    tvz: 55, zvp: 50, pvt: 45,
    description: '4인용, 전자 회로형 구조, 좁은 통로와 분기점이 많은 테란맵',
  ),
  MapData(
    name: '라르고',
    imageFile: '라르고.gif',
    rushDistance: 0.8,
    resources: 0.7,
    complexity: 0.4,
    tvz: 43, zvp: 57, pvt: 50,
    description: '4인용, 느린 전개 테마, 먼 러시거리와 넓은 지형으로 저그맵',
  ),
  MapData(
    name: '라만차',
    imageFile: '라만차.gif',
    rushDistance: 0.6,
    resources: 0.5,
    complexity: 0.65,
    tvz: 52, zvp: 59, pvt: 42,
    description: '상성맵, 풍차 능선 지형, 저그 선호',
  ),
  MapData(
    name: '라오발',
    imageFile: '라오발.gif',
    rushDistance: 0.5,
    resources: 0.4,
    complexity: 0.6,
    tvz: 62, zvp: 47, pvt: 50,
    description: '반언덕 멀티, 전형적 테란맵',
  ),
  MapData(
    name: '라이드오브발키리즈',
    imageFile: '라이드오브발키리즈.gif',
    rushDistance: 0.45,
    resources: 0.4,
    complexity: 0.6,
    tvz: 58, zvp: 48, pvt: 42,
    description: '멀티 확보 어렵고 초크 좁음, 테란맵',
  ),
  MapData(
    name: '라캄파넬라',
    imageFile: '라캄파넬라.gif',
    rushDistance: 0.6,
    resources: 0.6,
    complexity: 0.7,
    tvz: 50, zvp: 48, pvt: 55,
    description: '4인용, 종소리 테마, 언덕 구조와 고저차가 큰 토스맵',
  ),
  MapData(
    name: '러시아워3',
    imageFile: '러시아워3.gif',
    rushDistance: 0.4,
    resources: 0.6,
    complexity: 0.7,
    tvz: 59, zvp: 59, pvt: 44,
    description: '회전식 지형, 테란맵, 토스 불리',
  ),
  MapData(
    name: '레몬',
    imageFile: '레몬.gif',
    rushDistance: 0.5,
    resources: 0.6,
    complexity: 0.3,
    tvz: 50, zvp: 50, pvt: 50,
    description: '4인용, 과일 테마, 단순 대칭 구조의 밸런스 개념맵',
  ),
  MapData(
    name: '레이드어썰트2',
    imageFile: '레이드어썰트2.gif',
    rushDistance: 0.5,
    resources: 0.5,
    complexity: 0.7,
    tvz: 39, zvp: 65, pvt: 65,
    description: '이중입구 앞마당, 저그맵',
  ),
  MapData(
    name: '레퀴엠',
    imageFile: '레퀴엠.gif',
    rushDistance: 0.2,
    resources: 0.3,
    complexity: 0.4,
    tvz: 57, zvp: 42, pvt: 59,
    description: '극단적 짧은 거리, 역언덕 압박형',
  ),
  MapData(
    name: '레트로',
    imageFile: '레트로.gif',
    rushDistance: 0.6,
    resources: 0.6,
    complexity: 0.5,
    tvz: 52, zvp: 50, pvt: 48,
    description: '4인용, 복고 테마, 클래식 구조와 밸런스를 지향한 개념맵',
  ),
  MapData(
    name: '로드런너',
    imageFile: '로드런너.gif',
    rushDistance: 0.4,
    resources: 0.6,
    complexity: 0.5,
    tvz: 52, zvp: 57, pvt: 35,
    description: '다리+중립건물, 토스 불리',
  ),
  MapData(
    name: '로드킬',
    imageFile: '로드킬.gif',
    rushDistance: 0.4,
    resources: 0.5,
    complexity: 0.5,
    tvz: 58, zvp: 50, pvt: 42,
    description: '4인용, 도로 테마, 직선형 러시거리가 짧아 테란 기계화 강세',
  ),
  MapData(
    name: '로스트템플',
    imageFile: '로스트템플.gif',
    rushDistance: 0.6,
    resources: 0.6,
    complexity: 0.6,
    tvz: 55, zvp: 48, pvt: 48,
    description: '4인용, 클래식 맵의 원조, 섬멀티와 위치빨이 존재하는 국민맵',
  ),
  MapData(
    name: '로키',
    imageFile: '로키.gif',
    rushDistance: 0.5,
    resources: 0.7,
    complexity: 0.6,
    tvz: 65, zvp: 35, pvt: 53,
    description: '가스 풍부, 길목 난전맵, 토스맵',
  ),
  MapData(
    name: '롱기누스2',
    imageFile: '롱기누스2.gif',
    rushDistance: 0.6,
    resources: 0.8,
    complexity: 0.5,
    tvz: 60, zvp: 35, pvt: 43,
    description: '3인용, 본진10미넬, 2가스멀티, 테란맵',
  ),
  MapData(
    name: '루나',
    imageFile: '루나.gif',
    rushDistance: 0.7,
    resources: 0.6,
    complexity: 0.3,
    tvz: 42, zvp: 60, pvt: 60,
    description: '단순 구조 국민맵, 저그/토스 유리',
  ),
  MapData(
    name: '리버스템플',
    imageFile: '리버스템플.gif',
    rushDistance: 0.5,
    resources: 0.5,
    complexity: 0.6,
    tvz: 62, zvp: 47, pvt: 55,
    description: '로스트템플 반전, 테란 유리',
  ),
  MapData(
    name: '리버오브플레임',
    imageFile: '리버오브플레임.gif',
    rushDistance: 0.5,
    resources: 0.5,
    complexity: 0.8,
    tvz: 50, zvp: 46, pvt: 56,
    description: '4인용, 불의 강 테마, 용암 지형과 좁은 다리로 스플래시 유리한 토스맵',
  ),
  MapData(
    name: '리볼버',
    imageFile: '리볼버.gif',
    rushDistance: 0.6,
    resources: 0.7,
    complexity: 0.6,
    tvz: 46, zvp: 55, pvt: 50,
    description: '4인용, 회전식 6방향 진출로, 다중 경로로 견제 활발한 저그맵',
  ),
  MapData(
    name: '리트머스',
    imageFile: '리트머스.gif',
    rushDistance: 0.5,
    resources: 0.6,
    complexity: 0.5,
    tvz: 52, zvp: 53, pvt: 49,
    description: '대칭형 균형맵, 상성 편향 적은 개념맵',
  ),
  MapData(
    name: '리프더스톰',
    imageFile: '리프더스톰.gif',
    rushDistance: 0.5,
    resources: 0.55,
    complexity: 0.7,
    tvz: 43, zvp: 57, pvt: 50,
    description: '3인용, 다중 경로로 방어 어려움, 저글링 런바이 유리한 저그맵',
  ),
  MapData(
    name: '링잉블룸',
    imageFile: '링잉블룸.gif',
    rushDistance: 0.7,
    resources: 0.7,
    complexity: 0.4,
    tvz: 44, zvp: 56, pvt: 50,
    description: '4인용, 꽃 테마 원형 구조, 개방적 지형과 먼 멀티로 저그 유리',
  ),

  // ㅁ
  MapData(
    name: '매치포인트',
    imageFile: '매치포인트.gif',
    rushDistance: 0.65,
    resources: 0.4,
    complexity: 0.7,
    tvz: 55, zvp: 58, pvt: 42,
    description: '다양한 공격루트, 고지형 난전맵',
  ),
  MapData(
    name: '머큐리',
    imageFile: '머큐리.gif',
    rushDistance: 0.75,
    resources: 0.35,
    complexity: 0.6,
    tvz: 49, zvp: 65, pvt: 40,
    description: '좁은 입구, 저그 유리',
  ),
  MapData(
    name: '멀티버스',
    imageFile: '멀티버스.gif',
    rushDistance: 0.7,
    resources: 0.7,
    complexity: 0.7,
    tvz: 45, zvp: 55, pvt: 48,
    description: '4인용, 다중 우주 테마, 다중 경로와 다양한 멀티 루트로 저그 선호',
  ),
  MapData(
    name: '메두사',
    imageFile: '메두사.gif',
    rushDistance: 0.5,
    resources: 0.6,
    complexity: 0.7,
    tvz: 57, zvp: 42, pvt: 65,
    description: '뒷문+중립건물, 드롭 플레이 중요',
  ),
  MapData(
    name: '메타버스',
    imageFile: '메타버스.gif',
    rushDistance: 0.6,
    resources: 0.6,
    complexity: 0.8,
    tvz: 50, zvp: 48, pvt: 54,
    description: '4인용, 가상현실 테마, 복잡한 구조와 다층 지형으로 토스 약간 유리',
  ),
  MapData(
    name: '메트로폴리스',
    imageFile: '메트로폴리스.gif',
    rushDistance: 0.5,
    resources: 0.6,
    complexity: 0.8,
    tvz: 54, zvp: 50, pvt: 46,
    description: '4인용, 대도시 테마, 복잡한 도시 구조와 좁은 길목으로 테란 약간 유리',
  ),
  MapData(
    name: '멜트다운',
    imageFile: '멜트다운.gif',
    rushDistance: 0.6,
    resources: 0.65,
    complexity: 0.8,
    tvz: 50, zvp: 50, pvt: 50,
    description: '3인용, 핵발전소 테마, 중립건물과 복잡한 구조의 균형 개념맵',
  ),
  MapData(
    name: '모노폴리',
    imageFile: '모노폴리.gif',
    rushDistance: 0.6,
    resources: 0.45,
    complexity: 0.65,
    tvz: 47, zvp: 58, pvt: 45,
    description: '3인용, 자원 편중 구조, 멀티 쟁탈이 승패 결정, 저그 유리',
  ),
  MapData(
    name: '몬테크리스토',
    imageFile: '몬테크리스토.gif',
    rushDistance: 0.7,
    resources: 0.7,
    complexity: 0.8,
    tvz: 45, zvp: 45, pvt: 60,
    description: '중앙 신전, 아일랜드멀티, 토스맵',
  ),
  MapData(
    name: '몬티홀',
    imageFile: '몬티홀.gif',
    rushDistance: 0.3,
    resources: 0.8,
    complexity: 0.7,
    tvz: 61, zvp: 40, pvt: 55,
    description: '3갈래 미네랄 봉쇄, 테란맵',
  ),
  MapData(
    name: '몽환',
    imageFile: '몽환.gif',
    rushDistance: 0.5,
    resources: 0.6,
    complexity: 0.8,
    tvz: 45, zvp: 63, pvt: 48,
    description: '비대칭 4맵 조합, 위치빨 극심',
  ),
  MapData(
    name: '미스트',
    imageFile: '미스트.gif',
    rushDistance: 0.6,
    resources: 0.6,
    complexity: 0.6,
    tvz: 48, zvp: 55, pvt: 48,
    description: '안개 타일셋, 넓은 중앙으로 뮤탈 활용 유리한 저그맵',
  ),
  MapData(
    name: '민스트럴',
    imageFile: '민스트럴.gif',
    rushDistance: 0.55,
    resources: 0.6,
    complexity: 0.6,
    tvz: 48, zvp: 45, pvt: 55,
    description: '중앙 고지대 쟁탈전 중심, 하이템플러 활용 유리한 토스맵',
  ),

  // ㅂ
  MapData(
    name: '바람의계곡',
    imageFile: '바람의계곡.gif',
    rushDistance: 0.65,
    resources: 0.7,
    complexity: 0.5,
    tvz: 45, zvp: 56, pvt: 52,
    description: '넓은 계곡 지형, 멀티 풍부하여 저그 유리',
  ),
  MapData(
    name: '바이웨이',
    imageFile: '바이웨이.gif',
    rushDistance: 0.5,
    resources: 0.55,
    complexity: 0.6,
    tvz: 52, zvp: 48, pvt: 52,
    description: '우회로 테마, 다중 경로로 견제 용이한 균형맵',
  ),
  MapData(
    name: '발해의꿈',
    imageFile: '발해의꿈.gif',
    rushDistance: 0.8,
    resources: 0.8,
    complexity: 0.5,
    tvz: 40, zvp: 60, pvt: 48,
    description: '4인용, 한국 역사 테마, 넓은 영토와 풍부한 자원의 매크로 저그맵',
  ),
  MapData(
    name: '배틀로얄',
    imageFile: '배틀로얄.gif',
    rushDistance: 0.4,
    resources: 0.3,
    complexity: 0.5,
    tvz: 50, zvp: 65, pvt: 35,
    description: '극단적 저그맵, 테란·토스 불리',
  ),
  MapData(
    name: '백마고지',
    imageFile: '백마고지.gif',
    rushDistance: 0.6,
    resources: 0.8,
    complexity: 0.7,
    tvz: 55, zvp: 40, pvt: 65,
    description: '본진 2가스, 말 모양 고지대, 토스맵',
  ),
  MapData(
    name: '뱀파이어',
    imageFile: '뱀파이어.gif',
    rushDistance: 0.6,
    resources: 0.5,
    complexity: 0.7,
    tvz: 46, zvp: 54, pvt: 48,
    description: '4인용, 흡혈귀 테마, 어두운 지형과 매복 유리한 구조로 저그 선호',
  ),
  MapData(
    name: '버미어',
    imageFile: '버미어.gif',
    rushDistance: 0.6,
    resources: 0.6,
    complexity: 0.5,
    tvz: 50, zvp: 50, pvt: 50,
    description: '4인용, 화가 테마, 예술적 대칭 구조의 밸런스 개념맵',
  ),
  MapData(
    name: '버터',
    imageFile: '버터.gif',
    rushDistance: 0.4,
    resources: 0.5,
    complexity: 0.4,
    tvz: 55, zvp: 53, pvt: 47,
    description: '단순 구조 짧은 거리, 초반 압박 유리한 테란맵',
  ),
  MapData(
    name: '버티고',
    imageFile: '버티고.gif',
    rushDistance: 0.5,
    resources: 0.6,
    complexity: 0.7,
    tvz: 50, zvp: 46, pvt: 56,
    description: '4인용, 현기증 테마, 고저차 큰 지형으로 리버/탱크 운영 유리한 토스맵',
  ),
  MapData(
    name: '벤젠',
    imageFile: '벤젠.gif',
    rushDistance: 0.85,
    resources: 0.6,
    complexity: 0.5,
    tvz: 48, zvp: 49, pvt: 49,
    description: '매우 긴 러시거리, 테란맵',
  ),
  MapData(
    name: '블레이드스톰',
    imageFile: '블레이드스톰.gif',
    rushDistance: 0.4,
    resources: 0.5,
    complexity: 0.6,
    tvz: 57, zvp: 50, pvt: 44,
    description: '4인용, 칼바람 테마, 공격적 지형과 짧은 러시거리로 테란맵',
  ),
  MapData(
    name: '블레이즈',
    imageFile: '블레이즈.gif',
    rushDistance: 0.4,
    resources: 0.5,
    complexity: 0.7,
    tvz: 52, zvp: 46, pvt: 56,
    description: '4인용, 화염 테마, 좁은 통로에서 스플래시 유닛 극유리, 토스맵',
  ),
  MapData(
    name: '블록체인',
    imageFile: '블록체인.gif',
    rushDistance: 0.6,
    resources: 0.6,
    complexity: 0.7,
    tvz: 48, zvp: 50, pvt: 52,
    description: '4인용, 연결 블록 테마, 분할 구조로 멀티 관리가 중요한 운영맵',
  ),
  MapData(
    name: '블루스톰',
    imageFile: '블루스톰.gif',
    rushDistance: 0.4,
    resources: 0.7,
    complexity: 0.7,
    tvz: 47, zvp: 50, pvt: 50,
    description: '반땅 구도, 장기전 유도, 개념맵',
  ),
  MapData(
    name: '블리츠X',
    imageFile: '블리츠X.gif',
    rushDistance: 0.8,
    resources: 0.6,
    complexity: 0.7,
    tvz: 48, zvp: 57, pvt: 40,
    description: '먼 러시거리, X자 미네랄 구조',
  ),
  MapData(
    name: '비상-드림라이너',
    imageFile: '비상-드림라이너.gif',
    rushDistance: 0.6,
    resources: 0.65,
    complexity: 0.6,
    tvz: 48, zvp: 53, pvt: 48,
    description: '활주로형 중앙, 멀티 확장 용이한 저그 약유리맵',
  ),
  MapData(
    name: '비잔티움2',
    imageFile: '비잔티움2.gif',
    rushDistance: 0.5,
    resources: 0.7,
    complexity: 0.6,
    tvz: 45, zvp: 65, pvt: 45,
    description: '역언덕, 미네랄멀티 쟁탈전, 저그맵',
  ),
  MapData(
    name: '비프로스트3',
    imageFile: '비프로스트3.gif',
    rushDistance: 0.3,
    resources: 0.5,
    complexity: 0.7,
    tvz: 48, zvp: 62, pvt: 57,
    description: '램프없는 초크, 저그/토스 유리',
  ),

  // ㅅ
  MapData(
    name: '사우론',
    imageFile: '사우론.gif',
    rushDistance: 0.6,
    resources: 0.6,
    complexity: 0.7,
    tvz: 48, zvp: 46, pvt: 55,
    description: '4인용, 중앙 탑 구조의 어둠 테마, 고지대 확보가 핵심인 토스맵',
  ),
  MapData(
    name: '사일런트볼텍스',
    imageFile: '사일런트볼텍스.gif',
    rushDistance: 0.7,
    resources: 0.6,
    complexity: 0.6,
    tvz: 44, zvp: 56, pvt: 48,
    description: '4인용, 소용돌이 회전 구조, 먼 러시거리와 다중 경로로 저그 유리',
  ),
  MapData(
    name: '살라맨더',
    imageFile: '살라맨더.gif',
    rushDistance: 0.5,
    resources: 0.5,
    complexity: 0.7,
    tvz: 50, zvp: 46, pvt: 56,
    description: '4인용, 불도마뱀 테마 용암 지형, 좁은 초크와 언덕이 많은 토스맵',
  ),
  MapData(
    name: '샤쿠라스템플',
    imageFile: '샤쿠라스템플.gif',
    rushDistance: 0.6,
    resources: 0.7,
    complexity: 0.5,
    tvz: 48, zvp: 52, pvt: 50,
    description: '4인용, 스타2 참조 유명맵, 섬멀티와 넓은 중앙의 밸런스맵',
  ),
  MapData(
    name: '성안길',
    imageFile: '성안길.gif',
    rushDistance: 0.4,
    resources: 0.5,
    complexity: 0.8,
    tvz: 56, zvp: 50, pvt: 44,
    description: '4인용, 한국 도시 테마, 좁은 골목 구조로 스플래시 유리한 테란맵',
  ),
  MapData(
    name: '쇼다운',
    imageFile: '쇼다운.gif',
    rushDistance: 0.35,
    resources: 0.5,
    complexity: 0.5,
    tvz: 56, zvp: 48, pvt: 45,
    description: '짧은 러시거리 결투형, 초반 교전 중심 테란맵',
  ),
  MapData(
    name: '스노우바운드',
    imageFile: '스노우바운드.gif',
    rushDistance: 0.7,
    resources: 0.6,
    complexity: 0.6,
    tvz: 44, zvp: 56, pvt: 48,
    description: '4인용, 눈에 갇힌 테마, 이동 제한과 먼 러시거리로 저그맵',
  ),
  MapData(
    name: '스카이브릿지',
    imageFile: '스카이브릿지.gif',
    rushDistance: 0.65,
    resources: 0.6,
    complexity: 0.7,
    tvz: 53, zvp: 45, pvt: 57,
    description: '3인용, 고지대 다리 연결 구조, 드랍 플레이와 리콜 중요한 토스맵',
  ),
  MapData(
    name: '스파클',
    imageFile: '스파클.gif',
    rushDistance: 0.6,
    resources: 0.65,
    complexity: 0.4,
    tvz: 48, zvp: 52, pvt: 50,
    description: '밝은 타일셋의 개방적 4인맵, 넓은 센터와 개방된 멀티',
  ),
  MapData(
    name: '스페이스오디세이',
    imageFile: '스페이스오디세이.gif',
    rushDistance: 0.8,
    resources: 0.7,
    complexity: 0.6,
    tvz: 43, zvp: 58, pvt: 50,
    description: '우주 타일셋 대형맵, 긴 러시거리로 저그 유리',
  ),
  MapData(
    name: '시메트리오브싸이',
    imageFile: '시메트리오브싸이.gif',
    rushDistance: 0.55,
    resources: 0.6,
    complexity: 0.35,
    tvz: 50, zvp: 50, pvt: 50,
    description: '완전 대칭 구조, 위치빨 없는 균형맵',
  ),
  MapData(
    name: '시타델',
    imageFile: '시타델.gif',
    rushDistance: 0.5,
    resources: 0.55,
    complexity: 0.7,
    tvz: 56, zvp: 45, pvt: 42,
    description: '성채 구조의 좁은 입구, 수비 유리한 테란맵',
  ),
  MapData(
    name: '신백두대간',
    imageFile: '신백두대간.gif',
    rushDistance: 0.6,
    resources: 0.7,
    complexity: 0.75,
    tvz: 56, zvp: 62, pvt: 40,
    description: '언덕 컨트롤이 승패 결정, 저그맵',
  ),
  MapData(
    name: '신용오름',
    imageFile: '신용오름.gif',
    rushDistance: 0.5,
    resources: 0.4,
    complexity: 0.6,
    tvz: 57, zvp: 65, pvt: 42,
    description: '난전 힘싸움맵, 위치운 중요, 저그맵',
  ),
  MapData(
    name: '신의정원',
    imageFile: '신의정원.gif',
    rushDistance: 0.7,
    resources: 0.5,
    complexity: 0.55,
    tvz: 50, zvp: 52, pvt: 48,
    description: '8인용 대형맵, 위치별 불균형',
  ),
  MapData(
    name: '신저격능선',
    imageFile: '신저격능선.gif',
    rushDistance: 0.5,
    resources: 0.6,
    complexity: 0.7,
    tvz: 46, zvp: 61, pvt: 48,
    description: '능선 지형, 러커 차단 유리, 저그맵',
  ),
  MapData(
    name: '신청풍명월',
    imageFile: '신청풍명월.gif',
    rushDistance: 0.7,
    resources: 0.8,
    complexity: 0.5,
    tvz: 40, zvp: 65, pvt: 48,
    description: '3가스 확보 용이, 저그맵',
  ),
  MapData(
    name: '신추풍령',
    imageFile: '신추풍령.gif',
    rushDistance: 0.6,
    resources: 0.6,
    complexity: 0.8,
    tvz: 55, zvp: 48, pvt: 52,
    description: '좁은 통로와 초크, 테란맵',
  ),
  MapData(
    name: '신태백산맥',
    imageFile: '신태백산맥.gif',
    rushDistance: 0.6,
    resources: 0.6,
    complexity: 0.75,
    tvz: 48, zvp: 56, pvt: 52,
    description: '산맥 능선 지형 복잡, 러커 포진 유리한 저그맵',
  ),
  MapData(
    name: '신태양의제국',
    imageFile: '신태양의제국.gif',
    rushDistance: 0.6,
    resources: 0.7,
    complexity: 0.7,
    tvz: 64, zvp: 50, pvt: 51,
    description: '전형적 테란맵, 언덕/능선 다수',
  ),
  MapData(
    name: '신피의능선',
    imageFile: '신피의능선.gif',
    rushDistance: 0.5,
    resources: 0.6,
    complexity: 0.7,
    tvz: 53, zvp: 55, pvt: 38,
    description: '센터 구릉지, 캐리어 유리, 토스 불리',
  ),
  MapData(
    name: '실피드',
    imageFile: '실피드.gif',
    rushDistance: 0.55,
    resources: 0.6,
    complexity: 0.4,
    tvz: 50, zvp: 52, pvt: 48,
    description: '3인용, 바람의 정령 테마, 개방적 지형에서 기동전 중심 균형맵',
  ),
  MapData(
    name: '심판의날',
    imageFile: '심판의날.gif',
    rushDistance: 0.4,
    resources: 0.8,
    complexity: 0.8,
    tvz: 48, zvp: 52, pvt: 50,
    description: '얇은 벽, 드랍 클리프, 3본진 자원풍부',
  ),

  // ㅆ
  MapData(
    name: '써킷브레이커',
    imageFile: '써킷브레이커.gif',
    rushDistance: 0.7,
    resources: 0.7,
    complexity: 0.5,
    tvz: 55, zvp: 42, pvt: 40,
    description: '넓은 지형, 미네랄 풍부, 가스 부족, 테란맵',
  ),

  // ㅇ
  MapData(
    name: '아발론',
    imageFile: '아발론.gif',
    rushDistance: 0.7,
    resources: 0.75,
    complexity: 0.7,
    tvz: 48, zvp: 50, pvt: 50,
    description: '섬 지형 포함 대형맵, 아일랜드 멀티와 드랍 루트 다양',
  ),
  MapData(
    name: '아방가르드',
    imageFile: '아방가르드.gif',
    rushDistance: 0.55,
    resources: 0.6,
    complexity: 0.8,
    tvz: 48, zvp: 55, pvt: 48,
    description: '비정형 구조의 독특한 맵, 복잡한 지형과 다중 진출로',
  ),
  MapData(
    name: '아우토반',
    imageFile: '아우토반.gif',
    rushDistance: 0.7,
    resources: 0.6,
    complexity: 0.4,
    tvz: 48, zvp: 55, pvt: 48,
    description: '직선형 긴 통로, 벌처 기동 유리하나 저그 약유리',
  ),
  MapData(
    name: '아웃사이더',
    imageFile: '아웃사이더.gif',
    rushDistance: 0.6,
    resources: 0.7,
    complexity: 0.7,
    tvz: 50, zvp: 48, pvt: 50,
    description: '링형 확장 배치, 전략적 운영맵',
  ),
  MapData(
    name: '아질리아',
    imageFile: '아질리아.gif',
    rushDistance: 0.65,
    resources: 0.7,
    complexity: 0.5,
    tvz: 45, zvp: 55, pvt: 50,
    description: '토스 행성 타일셋, 넓은 앞마당과 안정적 멀티 구조',
  ),
  MapData(
    name: '아카디아2',
    imageFile: '아카디아2.gif',
    rushDistance: 0.5,
    resources: 0.8,
    complexity: 0.4,
    tvz: 52, zvp: 48, pvt: 46,
    description: '미네랄 확장 쉬움, 매크로 중심',
  ),
  MapData(
    name: '아케론',
    imageFile: '아케론.gif',
    rushDistance: 0.5,
    resources: 0.55,
    complexity: 0.7,
    tvz: 48, zvp: 48, pvt: 55,
    description: '지옥강 테마, 복잡한 언덕과 절벽으로 토스 유리',
  ),
  MapData(
    name: '아테나2',
    imageFile: '아테나2.gif',
    rushDistance: 0.5,
    resources: 0.6,
    complexity: 0.5,
    tvz: 56, zvp: 35, pvt: 64,
    description: '3인용, 프로토스 유리',
  ),
  MapData(
    name: '아포칼립스',
    imageFile: '아포칼립스.gif',
    rushDistance: 0.55,
    resources: 0.5,
    complexity: 0.75,
    tvz: 46, zvp: 53, pvt: 52,
    description: '3인용, 종말 테마 비대칭 지형, 파괴된 구조물로 위치운 큰 변수맵',
  ),
  MapData(
    name: '악령의숲',
    imageFile: '악령의숲.gif',
    rushDistance: 0.6,
    resources: 0.55,
    complexity: 0.8,
    tvz: 42, zvp: 60, pvt: 48,
    description: '3인용, 숲 테마 시야 제한, 매복과 럴커 활용 유리한 저그맵',
  ),
  MapData(
    name: '안드로메다',
    imageFile: '안드로메다.gif',
    rushDistance: 0.8,
    resources: 0.8,
    complexity: 0.5,
    tvz: 42, zvp: 58, pvt: 55,
    description: '넓은 중앙, 섬멀티, 본진 5미네랄, 저그맵',
  ),
  MapData(
    name: '알레그로',
    imageFile: '알레그로.gif',
    rushDistance: 0.35,
    resources: 0.5,
    complexity: 0.5,
    tvz: 58, zvp: 45, pvt: 42,
    description: '짧은 러시거리의 속공맵, 초반 압박과 빠른 교전 유도',
  ),
  MapData(
    name: '알카노이드',
    imageFile: '알카노이드.gif',
    rushDistance: 0.5,
    resources: 0.6,
    complexity: 0.75,
    tvz: 53, zvp: 48, pvt: 48,
    description: '격자형 벽 구조, 좁은 통로와 다수의 초크포인트',
  ),
  MapData(
    name: '알케미스트',
    imageFile: '알케미스트.gif',
    rushDistance: 0.6,
    resources: 0.75,
    complexity: 0.6,
    tvz: 48, zvp: 48, pvt: 55,
    description: '3인용, 가스 풍부하여 테크 중심, 하이템플러/디파일러 전략 유리한 토스맵',
  ),
  MapData(
    name: '알포인트',
    imageFile: '알포인트.gif',
    rushDistance: 0.5,
    resources: 0.6,
    complexity: 0.6,
    tvz: 62, zvp: 52, pvt: 49,
    description: '테란맵, 반언덕멀티, 3해처리 강제',
  ),
  MapData(
    name: '어나더데이',
    imageFile: '어나더데이.gif',
    rushDistance: 0.6,
    resources: 0.6,
    complexity: 0.5,
    tvz: 50, zvp: 50, pvt: 50,
    description: '3인용, 균형적 대칭 구조의 표준 개념맵, 실력 차이가 승패 결정',
  ),
  MapData(
    name: '어센션',
    imageFile: '어센션.gif',
    rushDistance: 0.6,
    resources: 0.55,
    complexity: 0.7,
    tvz: 56, zvp: 44, pvt: 55,
    description: '3인용, 고지대 중심 언덕 전투, 시즈탱크와 리버 포지션 중요',
  ),
  MapData(
    name: '얼터너티브',
    imageFile: '얼터너티브.gif',
    rushDistance: 0.4,
    resources: 0.7,
    complexity: 0.8,
    tvz: 35, zvp: 52, pvt: 65,
    description: '뒷문 개방 가능, 테란 약세',
  ),
  MapData(
    name: '얼티메이텀',
    imageFile: '얼티메이텀.gif',
    rushDistance: 0.4,
    resources: 0.55,
    complexity: 0.6,
    tvz: 57, zvp: 48, pvt: 42,
    description: '공격적 구조의 속공맵, 짧은 거리와 개방된 센터',
  ),
  MapData(
    name: '얼티메이트스트림',
    imageFile: '얼티메이트스트림.gif',
    rushDistance: 0.7,
    resources: 0.7,
    complexity: 0.65,
    tvz: 44, zvp: 57, pvt: 55,
    description: '물 지형이 맵을 분할, 긴 러시거리와 다리 쟁탈전',
  ),
  MapData(
    name: '에디',
    imageFile: '에디.gif',
    rushDistance: 0.55,
    resources: 0.6,
    complexity: 0.65,
    tvz: 50, zvp: 52, pvt: 48,
    description: '소용돌이 형태의 회전 구조, 센터 난전 유도',
  ),
  MapData(
    name: '에스컬레이드',
    imageFile: '에스컬레이드.gif',
    rushDistance: 0.5,
    resources: 0.55,
    complexity: 0.75,
    tvz: 55, zvp: 44, pvt: 50,
    description: '고지대 중심 등반형 맵, 탱크와 리버 시즈 핵심',
  ),
  MapData(
    name: '에스트렐라',
    imageFile: '에스트렐라.gif',
    rushDistance: 0.6,
    resources: 0.65,
    complexity: 0.55,
    tvz: 46, zvp: 55, pvt: 50,
    description: '별 모양 5갈래 구조, 다양한 진출로와 뮤탈 활용 유리',
  ),
  MapData(
    name: '엔드리스레이크',
    imageFile: '엔드리스레이크.gif',
    rushDistance: 0.75,
    resources: 0.7,
    complexity: 0.6,
    tvz: 42, zvp: 60, pvt: 52,
    description: '넓은 호수 지형으로 분리된 맵, 긴 러시거리 저그맵',
  ),
  MapData(
    name: '엔터더드래곤',
    imageFile: '엔터더드래곤.gif',
    rushDistance: 0.5,
    resources: 0.6,
    complexity: 0.65,
    tvz: 55, zvp: 55, pvt: 48,
    description: '용 형상 지형, 중앙 고지대 선점이 핵심',
  ),
  MapData(
    name: '엘니뇨',
    imageFile: '엘니뇨.gif',
    rushDistance: 0.65,
    resources: 0.65,
    complexity: 0.65,
    tvz: 44, zvp: 56, pvt: 52,
    description: '3인용, 해류 테마 물 지형 다수, 섬멀티와 셔틀/드랍십 운용 중요',
  ),
  MapData(
    name: '엘리시온',
    imageFile: '엘리시온.gif',
    rushDistance: 0.65,
    resources: 0.8,
    complexity: 0.5,
    tvz: 44, zvp: 56, pvt: 55,
    description: '풍부한 자원의 낙원형 맵, 3가스 확보 용이한 저그맵',
  ),
  MapData(
    name: '오델로',
    imageFile: '오델로.gif',
    rushDistance: 0.5,
    resources: 0.8,
    complexity: 0.4,
    tvz: 65, zvp: 55, pvt: 35,
    description: '테란맵, 탱크 길목 중심',
  ),
  MapData(
    name: '오드아이',
    imageFile: '오드아이.gif',
    rushDistance: 0.55,
    resources: 0.6,
    complexity: 0.6,
    tvz: 47, zvp: 44, pvt: 55,
    description: '비대칭 시야 구조, 리콜 활용 유리한 토스맵',
  ),
  MapData(
    name: '오디세이',
    imageFile: '오디세이.gif',
    rushDistance: 0.65,
    resources: 0.7,
    complexity: 0.6,
    tvz: 45, zvp: 55, pvt: 52,
    description: '긴 여정 테마, 넓은 지형과 풍부한 멀티로 저그맵',
  ),
  MapData(
    name: '오딘',
    imageFile: '오딘.gif',
    rushDistance: 0.7,
    resources: 0.75,
    complexity: 0.65,
    tvz: 42, zvp: 58, pvt: 55,
    description: '거대한 지형의 북유럽 테마, 넓은 센터와 다수 멀티',
  ),
  MapData(
    name: '오버워치',
    imageFile: '오버워치.gif',
    rushDistance: 0.7,
    resources: 0.7,
    complexity: 0.65,
    tvz: 47, zvp: 55, pvt: 52,
    description: '넓은 맵, 고지대 시야 중요하며 저그 유리',
  ),
  MapData(
    name: '옵티마이저',
    imageFile: '옵티마이저.gif',
    rushDistance: 0.55,
    resources: 0.6,
    complexity: 0.45,
    tvz: 50, zvp: 50, pvt: 50,
    description: '효율적 동선의 균형맵, 모든 종족 공평한 구조',
  ),
  MapData(
    name: '왕의귀환',
    imageFile: '왕의귀환.gif',
    rushDistance: 0.6,
    resources: 0.7,
    complexity: 0.6,
    tvz: 52, zvp: 48, pvt: 35,
    description: '본진 섬확장, 좁은 계곡, 테프전 테란맵',
  ),
  MapData(
    name: '용오름',
    imageFile: '용오름.gif',
    rushDistance: 0.5,
    resources: 0.55,
    complexity: 0.7,
    tvz: 52, zvp: 56, pvt: 48,
    description: '용오름 형태의 나선형 지형, 센터 고지대 쟁탈전',
  ),
  MapData(
    name: '우산국',
    imageFile: '우산국.gif',
    rushDistance: 0.65,
    resources: 0.6,
    complexity: 0.7,
    tvz: 48, zvp: 48, pvt: 55,
    description: '섬 구조 포함 해양맵, 아일랜드 멀티와 드랍 필수',
  ),
  MapData(
    name: '우지사라',
    imageFile: '우지사라.gif',
    rushDistance: 0.7,
    resources: 0.7,
    complexity: 0.45,
    tvz: 44, zvp: 58, pvt: 48,
    description: '3인용, 아프리카 테마 넓은 지형, 매크로 중심 장기전, 저그 유리',
  ),
  MapData(
    name: '운고로',
    imageFile: '운고로.gif',
    rushDistance: 0.5,
    resources: 0.6,
    complexity: 0.5,
    tvz: 55, zvp: 65, pvt: 35,
    description: '저그맵, 토스 불리, 다가스 유리',
  ),
  MapData(
    name: '울돌목',
    imageFile: '울돌목.gif',
    rushDistance: 0.35,
    resources: 0.5,
    complexity: 0.7,
    tvz: 58, zvp: 48, pvt: 42,
    description: '극좁은 해협 초크, 시즈탱크 봉쇄 극강 테란맵',
  ),
  MapData(
    name: '워프게이트',
    imageFile: '워프게이트.gif',
    rushDistance: 0.45,
    resources: 0.6,
    complexity: 0.65,
    tvz: 55, zvp: 50, pvt: 48,
    description: '순간이동 포인트 콘셉트, 다중 진입로와 기습 루트',
  ),
  MapData(
    name: '위시본',
    imageFile: '위시본.gif',
    rushDistance: 0.55,
    resources: 0.55,
    complexity: 0.6,
    tvz: 50, zvp: 53, pvt: 48,
    description: 'Y자 분기 구조, 위치에 따라 근거리/원거리 가변',
  ),
  MapData(
    name: '유보트',
    imageFile: '유보트.gif',
    rushDistance: 0.7,
    resources: 0.65,
    complexity: 0.7,
    tvz: 46, zvp: 52, pvt: 55,
    description: '물/섬 지형의 해양맵, 아일랜드 멀티와 공중전 중요',
  ),
  MapData(
    name: '이너코븐',
    imageFile: '이너코븐.gif',
    rushDistance: 0.5,
    resources: 0.5,
    complexity: 0.8,
    tvz: 52, zvp: 47, pvt: 53,
    description: '3인용, 좁은 통로와 매복 지형, 스플래시 유닛 강세',
  ),
  MapData(
    name: '이카루스',
    imageFile: '이카루스.gif',
    rushDistance: 0.5,
    resources: 0.6,
    complexity: 0.5,
    tvz: 48, zvp: 59, pvt: 46,
    description: '저그맵, 우주타일셋, 뮤탈 활용 유리',
  ),
  MapData(
    name: '이클립스',
    imageFile: '이클립스.gif',
    rushDistance: 0.6,
    resources: 0.6,
    complexity: 0.5,
    tvz: 48, zvp: 53, pvt: 48,
    description: '일식 테마 우주맵, 개방적 중앙으로 저그 약유리',
  ),
  MapData(
    name: '인디안라멘트',
    imageFile: '인디안라멘트.gif',
    rushDistance: 0.6,
    resources: 0.5,
    complexity: 0.7,
    tvz: 48, zvp: 55, pvt: 48,
    description: '비가 테마, 능선 지형과 다중 경로로 저그 약유리',
  ),
  MapData(
    name: '인베이더',
    imageFile: '인베이더.gif',
    rushDistance: 0.45,
    resources: 0.55,
    complexity: 0.6,
    tvz: 56, zvp: 48, pvt: 42,
    description: '침략자 테마, 좁은 초크로 방어전 유리한 테란맵',
  ),
  MapData(
    name: '인큐버스',
    imageFile: '인큐버스.gif',
    rushDistance: 0.45,
    resources: 0.5,
    complexity: 0.8,
    tvz: 58, zvp: 46, pvt: 42,
    description: '어두운 지형의 복잡한 맵, 좁은 통로와 기습 유리',
  ),
  MapData(
    name: '인투더다크니스',
    imageFile: '인투더다크니스.gif',
    rushDistance: 0.55,
    resources: 0.55,
    complexity: 0.65,
    tvz: 49, zvp: 49, pvt: 49,
    description: '어둠 속 진입 테마, 다중 경로와 언덕 활용 균형맵',
  ),

  // ㅈ
  MapData(
    name: '자이언트스텝',
    imageFile: '자이언트스텝.gif',
    rushDistance: 0.7,
    resources: 0.65,
    complexity: 0.5,
    tvz: 44, zvp: 56, pvt: 52,
    description: '넓은 보폭 테마, 먼 거리와 넓은 지형으로 저그맵',
  ),
  MapData(
    name: '정글스토리',
    imageFile: '정글스토리.gif',
    rushDistance: 0.6,
    resources: 0.65,
    complexity: 0.85,
    tvz: 46, zvp: 55, pvt: 50,
    description: '울창한 정글 테마, 높은 복잡도와 다중 우회로',
  ),
  MapData(
    name: '제3세계',
    imageFile: '제3세계.gif',
    rushDistance: 0.55,
    resources: 0.5,
    complexity: 0.65,
    tvz: 50, zvp: 50, pvt: 50,
    description: '제3세계 테마, 자원 부족 환경의 균형맵',
  ),
  MapData(
    name: '제노스카이',
    imageFile: '제노스카이.gif',
    rushDistance: 0.65,
    resources: 0.6,
    complexity: 0.55,
    tvz: 44, zvp: 56, pvt: 52,
    description: '외계 하늘 우주 타일셋, 넓은 센터와 뮤탈 활용 유리',
  ),
  MapData(
    name: '조디악',
    imageFile: '조디악.gif',
    rushDistance: 0.6,
    resources: 0.8,
    complexity: 0.6,
    tvz: 52, zvp: 48, pvt: 50,
    description: '가스 멀티 중심 4인용, 섬멀티 2개 포함',
  ),
  MapData(
    name: '중원',
    imageFile: '중원.gif',
    rushDistance: 0.55,
    resources: 0.65,
    complexity: 0.5,
    tvz: 53, zvp: 50, pvt: 47,
    description: '3인용, 한국 역사 테마 중앙 평야, 대규모 교전 유도, 테란 약간 유리',
  ),
  MapData(
    name: '지오메트리',
    imageFile: '지오메트리.gif',
    rushDistance: 0.4,
    resources: 0.6,
    complexity: 0.5,
    tvz: 65, zvp: 45, pvt: 43,
    description: '테란맵, 저그·토스 불리',
  ),
  MapData(
    name: '짐레이너스메모리',
    imageFile: '짐레이너스메모리.gif',
    rushDistance: 0.55,
    resources: 0.65,
    complexity: 0.5,
    tvz: 50, zvp: 50, pvt: 50,
    description: '클래식 구조의 기념맵, 안정적 멀티와 균형 잡힌 지형',
  ),

  // ㅊ
  MapData(
    name: '채러티',
    imageFile: '채러티.gif',
    rushDistance: 0.6,
    resources: 0.6,
    complexity: 0.45,
    tvz: 50, zvp: 50, pvt: 50,
    description: '균형적 구조의 자선맵, 모든 종족에 공평한 지형',
  ),
  MapData(
    name: '챌린저',
    imageFile: '챌린저.gif',
    rushDistance: 0.5,
    resources: 0.6,
    complexity: 0.55,
    tvz: 49, zvp: 49, pvt: 49,
    description: '도전자 테마, 대칭형 공정한 구조의 균형맵',
  ),
  MapData(
    name: '철의장막',
    imageFile: '철의장막.gif',
    rushDistance: 0.45,
    resources: 0.5,
    complexity: 0.8,
    tvz: 60, zvp: 48, pvt: 40,
    description: '좁은 통로와 장벽 구조, 탱크 시즈와 초크 활용 테란맵',
  ),

  // ㅋ
  MapData(
    name: '카르타고',
    imageFile: '카르타고.gif',
    rushDistance: 0.5,
    resources: 0.7,
    complexity: 0.7,
    tvz: 35, zvp: 65, pvt: 45,
    description: '저그맵, 테란 불리, 넓은 지형과 멀티',
  ),
  MapData(
    name: '카멜롯',
    imageFile: '카멜롯.gif',
    rushDistance: 0.55,
    resources: 0.65,
    complexity: 0.7,
    tvz: 48, zvp: 48, pvt: 56,
    description: '성곽 테마, 언덕 방어 유리한 지형으로 토스맵',
  ),
  MapData(
    name: '카트리나',
    imageFile: '카트리나.gif',
    rushDistance: 0.5,
    resources: 0.6,
    complexity: 0.7,
    tvz: 56, zvp: 39, pvt: 53,
    description: '절벽 지형 많고 캐리어 유리, 저그 불리',
  ),
  MapData(
    name: '콜로세움2',
    imageFile: '콜로세움2.gif',
    rushDistance: 0.4,
    resources: 0.5,
    complexity: 0.6,
    tvz: 57, zvp: 47, pvt: 55,
    description: '좁은 초크와 높은 멀티, 테란 약간 유리',
  ),
  MapData(
    name: '크로스게임',
    imageFile: '크로스게임.gif',
    rushDistance: 0.5,
    resources: 0.6,
    complexity: 0.5,
    tvz: 53, zvp: 53, pvt: 48,
    description: '교차형 대칭 구조, 중앙 교전 중심 테란 약유리맵',
  ),
  MapData(
    name: '크로싱필드',
    imageFile: '크로싱필드.gif',
    rushDistance: 0.45,
    resources: 0.6,
    complexity: 0.55,
    tvz: 55, zvp: 47, pvt: 50,
    description: '교차 지형 구조, 중앙 교전이 핵심인 테란 약유리맵',
  ),
  MapData(
    name: '크림슨아일즈',
    imageFile: '크림슨아일즈.gif',
    rushDistance: 0.65,
    resources: 0.6,
    complexity: 0.7,
    tvz: 45, zvp: 50, pvt: 58,
    description: '3인용, 붉은 섬 테마, 아일랜드 멀티와 공중 유닛 핵심인 토스맵',
  ),
  MapData(
    name: '킥백',
    imageFile: '킥백.gif',
    rushDistance: 0.4,
    resources: 0.55,
    complexity: 0.55,
    tvz: 56, zvp: 46, pvt: 44,
    description: '짧은 거리의 속공맵, 빠른 교전과 초반 압박 유도',
  ),

  // ㅌ
  MapData(
    name: '타우크로스',
    imageFile: '타우크로스.gif',
    rushDistance: 0.6,
    resources: 0.7,
    complexity: 0.3,
    tvz: 50, zvp: 50, pvt: 52,
    description: '단순 구조 개념맵, 균형 잡힌 맵',
  ),
  MapData(
    name: '태풍의눈',
    imageFile: '태풍의눈.gif',
    rushDistance: 0.5,
    resources: 0.85,
    complexity: 0.6,
    tvz: 58, zvp: 48, pvt: 45,
    description: '자원 풍부, 벌쳐 견제 유리한 테란맵',
  ),
  MapData(
    name: '턴어라운드',
    imageFile: '턴어라운드.gif',
    rushDistance: 0.55,
    resources: 0.6,
    complexity: 0.6,
    tvz: 45, zvp: 45, pvt: 55,
    description: '회전 구조 동선, 셔틀 드랍 용이한 토스맵',
  ),
  MapData(
    name: '템페스트',
    imageFile: '템페스트.gif',
    rushDistance: 0.6,
    resources: 0.65,
    complexity: 0.5,
    tvz: 50, zvp: 50, pvt: 50,
    description: '유명 균형 4인맵, 거리 가변형 위치빨과 안정적 멀티',
  ),
  MapData(
    name: '투싼',
    imageFile: '투싼.gif',
    rushDistance: 0.75,
    resources: 0.7,
    complexity: 0.45,
    tvz: 42, zvp: 58, pvt: 55,
    description: '사막 도시 테마의 넓은 대형맵, 긴 러시거리 저그맵',
  ),
  MapData(
    name: '투혼',
    imageFile: '투혼.gif',
    rushDistance: 0.4,
    resources: 0.6,
    complexity: 0.4,
    tvz: 55, zvp: 48, pvt: 45,
    description: '짧은 러시거리, 테란 약간 유리한 국민맵',
  ),
  MapData(
    name: '트라이애슬론',
    imageFile: '트라이애슬론.gif',
    rushDistance: 0.4,
    resources: 0.6,
    complexity: 0.85,
    tvz: 52, zvp: 50, pvt: 48,
    description: '클로킹 에그 컨셉맵, 높은 복잡도',
  ),
  MapData(
    name: '트라이포드',
    imageFile: '트라이포드.gif',
    rushDistance: 0.6,
    resources: 0.6,
    complexity: 0.45,
    tvz: 50, zvp: 50, pvt: 50,
    description: '3인용, 3각 완전대칭 구조, 위치운 없는 순수 실력 균형맵',
  ),
  MapData(
    name: '트랜지스터',
    imageFile: '트랜지스터.gif',
    rushDistance: 0.55,
    resources: 0.55,
    complexity: 0.85,
    tvz: 54, zvp: 46, pvt: 54,
    description: '3인용, 전자회로 테마, 좁은 초크와 복잡한 구조, 스플래시 유닛 중요',
  ),
  MapData(
    name: '트레스패스',
    imageFile: '트레스패스.gif',
    rushDistance: 0.45,
    resources: 0.5,
    complexity: 0.65,
    tvz: 55, zvp: 48, pvt: 45,
    description: '침입 테마, 좁은 진입로로 방어전 유리한 테란맵',
  ),
  MapData(
    name: '트로이',
    imageFile: '트로이.gif',
    rushDistance: 0.3,
    resources: 0.6,
    complexity: 0.9,
    tvz: 48, zvp: 42, pvt: 58,
    description: '토스 유리, 저그 최악, 매우 복잡한 지형',
  ),
  MapData(
    name: '티아매트',
    imageFile: '티아매트.gif',
    rushDistance: 0.45,
    resources: 0.65,
    complexity: 0.7,
    tvz: 65, zvp: 45, pvt: 52,
    description: 'TvZ 테란 유리, 저그 불리',
  ),

  // ㅍ
  MapData(
    name: '파라노이드안드로이드',
    imageFile: '파라노이드안드로이드.gif',
    rushDistance: 0.6,
    resources: 0.6,
    complexity: 0.7,
    tvz: 48, zvp: 52, pvt: 50,
    description: '편집증 테마, 복잡한 다중 경로와 시야 제한 구조',
  ),
  MapData(
    name: '파미르고원',
    imageFile: '파미르고원.gif',
    rushDistance: 0.75,
    resources: 0.6,
    complexity: 0.7,
    tvz: 42, zvp: 57, pvt: 55,
    description: '넓고 험한 고원 지형, 긴 러시거리와 고지대 쟁탈전',
  ),
  MapData(
    name: '파워본드',
    imageFile: '파워본드.gif',
    rushDistance: 0.55,
    resources: 0.55,
    complexity: 0.65,
    tvz: 55, zvp: 52, pvt: 46,
    description: '3인용, 에너지 연결 테마, 다리와 초크 중심 포지션 싸움, 테란 유리',
  ),
  MapData(
    name: '파이썬',
    imageFile: '파이썬.gif',
    rushDistance: 0.6,
    resources: 0.6,
    complexity: 0.5,
    tvz: 55, zvp: 54, pvt: 45,
    description: '거리 가변(근/중/장거리), 뮤탈 견제 용이',
  ),
  MapData(
    name: '판테온',
    imageFile: '판테온.gif',
    rushDistance: 0.55,
    resources: 0.7,
    complexity: 0.6,
    tvz: 50, zvp: 45, pvt: 55,
    description: '웅장한 신전 구조, 넓은 센터와 고지대 활용 토스맵',
  ),
  MapData(
    name: '팔진도',
    imageFile: '팔진도.gif',
    rushDistance: 0.6,
    resources: 0.65,
    complexity: 0.65,
    tvz: 50, zvp: 65, pvt: 35,
    description: '뒷마당 기반 후반 힘싸움맵, 저프전 저그 유리',
  ),
  MapData(
    name: '패러독스',
    imageFile: '패러독스.gif',
    rushDistance: 0.55,
    resources: 0.55,
    complexity: 0.65,
    tvz: 50, zvp: 48, pvt: 55,
    description: '역설 테마, 비대칭 대칭 구조로 토스 약유리',
  ),
  MapData(
    name: '패스파인더',
    imageFile: '패스파인더.gif',
    rushDistance: 0.55,
    resources: 0.55,
    complexity: 0.7,
    tvz: 48, zvp: 60, pvt: 55,
    description: '3인용 상성맵, 공중 가까워 뮤탈 강세',
  ),
  MapData(
    name: '페이스오프',
    imageFile: '페이스오프.gif',
    rushDistance: 0.5,
    resources: 0.6,
    complexity: 0.5,
    tvz: 49, zvp: 49, pvt: 49,
    description: '완전 대칭형, 순수 실력 대결 균형맵',
  ),
  MapData(
    name: '포트리스SE',
    imageFile: '포트리스SE.gif',
    rushDistance: 0.5,
    resources: 0.65,
    complexity: 0.7,
    tvz: 58, zvp: 58, pvt: 45,
    description: '전술형 힘싸움맵, 섬멀티와 리콜 전략 중요',
  ),
  MapData(
    name: '폭풍의언덕',
    imageFile: '폭풍의언덕.gif',
    rushDistance: 0.7,
    resources: 0.7,
    complexity: 0.4,
    tvz: 65, zvp: 45, pvt: 35,
    description: '평지 위주 개테란맵, 개방적 멀티',
  ),
  MapData(
    name: '폴라리스랩소디',
    imageFile: '폴라리스랩소디.gif',
    rushDistance: 0.6,
    resources: 0.5,
    complexity: 0.7,
    tvz: 58, zvp: 40, pvt: 60,
    description: '3갈래 진출로와 역언덕 구조의 토스맵',
  ),
  MapData(
    name: '폴리포이드',
    imageFile: '폴리포이드.gif',
    rushDistance: 0.5,
    resources: 0.6,
    complexity: 0.85,
    tvz: 50, zvp: 48, pvt: 50,
    description: '다면체 구조의 고복잡도 맵, 다수의 초크와 우회로',
  ),
  MapData(
    name: '폴스타',
    imageFile: '폴스타.gif',
    rushDistance: 0.5,
    resources: 0.65,
    complexity: 0.55,
    tvz: 52, zvp: 50, pvt: 48,
    description: '중앙 집중형 북극성 구조, 센터 쟁탈이 승패 결정',
  ),
  MapData(
    name: '플라즈마',
    imageFile: '플라즈마.gif',
    rushDistance: 0.4,
    resources: 0.4,
    complexity: 0.8,
    tvz: 60, zvp: 42, pvt: 48,
    description: '중립 에그 시간형 섬맵, 저그 불리',
  ),

  // ㅎ
  MapData(
    name: '하이웨이스타',
    imageFile: '하이웨이스타.gif',
    rushDistance: 0.65,
    resources: 0.6,
    complexity: 0.45,
    tvz: 46, zvp: 55, pvt: 52,
    description: '고속도로 테마 직선형, 먼 거리로 저그 유리',
  ),
  MapData(
    name: '핸더슨크레이터',
    imageFile: '핸더슨크레이터.gif',
    rushDistance: 0.6,
    resources: 0.6,
    complexity: 0.6,
    tvz: 50, zvp: 52, pvt: 48,
    description: '분화구 형태의 원형 구조, 센터 저지대 난전 유도',
  ),
  MapData(
    name: '현무',
    imageFile: '현무.gif',
    rushDistance: 0.65,
    resources: 0.6,
    complexity: 0.65,
    tvz: 44, zvp: 57, pvt: 52,
    description: '물/얼음 테마의 사신맵, 넓은 지형과 러커 운용 유리',
  ),
  MapData(
    name: '화랑도',
    imageFile: '화랑도.gif',
    rushDistance: 0.6,
    resources: 0.6,
    complexity: 0.7,
    tvz: 45, zvp: 58, pvt: 48,
    description: '앞마당 미네랄온리, 저그 유리한 2인용 대형맵',
  ),
  MapData(
    name: '화이트나이트',
    imageFile: '화이트나이트.gif',
    rushDistance: 0.55,
    resources: 0.65,
    complexity: 0.5,
    tvz: 52, zvp: 48, pvt: 48,
    description: '밝은 타일셋의 기사 테마, 개방된 센터와 능선 활용',
  ),
  MapData(
    name: '화이트아웃',
    imageFile: '화이트아웃.gif',
    rushDistance: 0.7,
    resources: 0.6,
    complexity: 0.55,
    tvz: 43, zvp: 57, pvt: 50,
    description: '3인용, 눈보라 테마 넓은 지형, 시야 제한, 먼 러시거리로 저그 유리',
  ),
  MapData(
    name: '황금의땅',
    imageFile: '황금의땅.gif',
    rushDistance: 0.65,
    resources: 0.9,
    complexity: 0.5,
    tvz: 44, zvp: 55, pvt: 52,
    description: '자원 매우 풍부한 황금 테마, 멀티 확장 쉬운 저그맵',
  ),
  MapData(
    name: '히치하이커',
    imageFile: '히치하이커.gif',
    rushDistance: 0.3,
    resources: 0.4,
    complexity: 0.8,
    tvz: 51, zvp: 47, pvt: 57,
    description: '좁은 통로와 중립건물, 초단거리 치즈맵',
  ),
];

/// 맵 이름으로 검색
MapData? getMapByName(String name) {
  try {
    return allMaps.firstWhere((m) => m.name == name);
  } catch (_) {
    return null;
  }
}

/// 이미지 파일명으로 검색
MapData? getMapByImageFile(String imageFile) {
  try {
    return allMaps.firstWhere((m) => m.imageFile == imageFile);
  } catch (_) {
    return null;
  }
}

/// 시즌별 추천 맵풀 (8개 맵 세트)
const Map<String, List<String>> seasonMapPools = {
  '2010_S1': [
    '투혼',
    '써킷브레이커',
    '신저격능선',
    '네오그라운드제로',
    '네오아웃라이어',
    '네오일렉트릭써킷',
    '네오체인리액션',
    '네오제이드',
  ],
  '2011_S1': [
    '투혼',
    '써킷브레이커',
    '벤젠',
    '이카루스',
    '트라이애슬론',
    '패스파인더',
    '라만차',
    '네오벨트웨이',
  ],
  '2012_S1': [
    '투혼',
    '써킷브레이커',
    '신저격능선',
    '네오그라운드제로',
    '네오아웃라이어',
    '네오일렉트릭써킷',
    '네오체인리액션',
    '네오제이드',
  ],
};

/// 랜덤 시즌맵풀 생성 (8개)
List<MapData> generateRandomSeasonMaps() {
  final shuffled = List<MapData>.from(allMaps)..shuffle();
  return shuffled.take(8).toList();
}

/// 밸런스 맵 (모든 종족 상성이 48~52 범위)
List<MapData> get balancedMaps => allMaps.where((m) =>
    m.tvz >= 48 && m.tvz <= 52 &&
    m.zvp >= 48 && m.zvp <= 52 &&
    m.pvt >= 48 && m.pvt <= 52
).toList();

/// 테란맵 (TvZ 55 이상)
List<MapData> get terranMaps => allMaps.where((m) => m.tvz >= 55).toList();

/// 저그맵 (ZvP 55 이상)
List<MapData> get zergMaps => allMaps.where((m) => m.zvp >= 55).toList();

/// 프로토스맵 (PvT 55 이상)
List<MapData> get protossMaps => allMaps.where((m) => m.pvt >= 55).toList();

